### ISSUE TITLE
[BUG] Provisioning service was throwing 500 Internal Server Error

### ISSUE THREAD

**Issue by puneetsinghnanda** [Telecominfraproject/wlan-cloud-owprov#53]
Hi,
Provisioning service goes down on 27th Aug 2022 and there were no supporting error or warning logs to understand the issue. On Provisioning UI, we can see below error. 
**Prov Service** and **Prov UI** logs are attached for reference.

![Provisioning service error screenshot](https://user-images.githubusercontent.com/105911469/187439445-f0c87082-e45c-4f35-a4a2-41e68cabfe19.png)

[prov-service-Logs.txt](https://github.com/Telecominfraproject/wlan-cloud-owprov/files/9452851/prov-service-Logs.txt)
[prov-uiLogs.txt](https://github.com/Telecominfraproject/wlan-cloud-owprov/files/9452854/prov-uiLogs.txt)

**Comment by stephb9959** [comment]
This issue had been addressed in 2.8.0 with better reporting.
